include_guard(GLOBAL)

if(NOT DEFINED C74_CXX_STANDARD)
    set(C74_CXX_STANDARD 0)
endif()

option(MAX_SDK_CODESIGN_EXTERNS "Sign macOS externs during build" ON)
# Use MAX_SDK_CODESIGN_IDENTITY to override the default ad-hoc identity "-"
# e.g. -DMAX_SDK_CODESIGN_IDENTITY="Developer ID Application: ..."

set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "$<$<CONFIG:Debug,RelWithDebInfo>:ProgramDatabase>")
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

# CMake 4.0 Adds CMAKE_MSVC_RUNTIME_CHECKS, like:
# set(CMAKE_MSVC_RUNTIME_CHECKS "$<$<CONFIG:Debug,RelWithDebInfo>:StackFrameErrorCheck;UninitializedVariable>")
add_compile_options($<$<AND:$<CONFIG:Debug>,$<CXX_COMPILER_ID:MSVC>>:/RTC1>)

set(CMAKE_SHARED_MODULE_SUFFIX ".mxl_${CMAKE_SYSTEM_PROCESSOR}")
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
  set(CMAKE_SHARED_MODULE_SUFFIX ".mxe64")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  unset(CMAKE_SHARED_MODULE_SUFFIX)
endif()

set_property(DIRECTORY PROPERTY BUNDLE_EXTENSION "mxo")

if(DEFINED C74_LIBRARY_OUTPUT_DIRECTORY)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${C74_LIBRARY_OUTPUT_DIRECTORY}")
elseif(NOT DEFINED C74_BUILD_MAX_EXTENSION)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/externals")
else()
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/extensions")
endif()
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")

if(WIN32)
    set(CMAKE_PDB_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/pdb/$<CONFIG>")
endif()

find_package(MaxSDK REQUIRED)
